openapi: 3.0.2
info:
  title: AwsomeElectricians
  version: "1.0"
servers:
  - url: https://api.server.test/v1
tags:
  - name: RequestForQuotation
    description: Everything about request for quotation
  - name: Project
    description: Everything about your Project
paths:
  /NewQuotationRequest:
    post:
      tags:
        - Quotation
      description: Recives a quotation request from a HRC company
      operationId: NewQuotationRequestPOST
      parameters:
        - name: Address
          in: query
          description: Address of the property
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: StartDate
          in: query
          description: Start Date
          required: true
          style: form
          explode: true
          schema:
            type: string
          example: 10/10/2023
        - name: Duration
          in: query
          description: Duration in days
          required: true
          style: form
          explode: true
          schema:
            type: integer
          example: 60
        - name: Budget
          in: query
          description: Max budget in Euroes
          required: true
          style: form
          explode: true
          schema:
            type: number
          example: 1000
      responses:
        "201":
          description: Request submitted successfuly.
        default:
          description: Exception happened!
      x-swagger-router-controller: Quotation

  /EditQuotation:
    put:
      tags:
        - Quotation
      description: Edit a request for quotation to constructor
      operationId: editQuotationPUT
      parameters:
        - name: QuotationRequestId
          in: query
          description: Id of the quotation request
          required: true
          style: form
          explode: true
          schema:
            type: integer
          example: 1
        - name: Address
          in: query
          description: Address of the property
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: StartDate
          in: query
          description: Start Date
          required: true
          style: form
          explode: true
          schema:
            type: string
          example: 10/10/2023
        - name: Duration
          in: query
          description: Duration in days
          required: true
          style: form
          explode: true
          schema:
            type: integer
          example: 60
        - name: Budget
          in: query
          description: Max budget in Euroes
          required: true
          style: form
          explode: true
          schema:
            type: number
          example: 1000
      responses:
        "200":
          description: Changes applied successfuly
        "404":
          description: Resource not found
        default:
          description: Exception happened!
      x-swagger-router-controller: Quotation
  /DeleteQuotationRequest/{id}:
    delete:
      tags:
        - Quotation
      description: delete a request for quotation to constructor
      operationId: deleteQuotationIdDELETE
      parameters:
        - name: id
          in: path
          description: Id of the quotation request
          required: true
          style: simple
          explode: false
          schema:
            type: integer
          example: 1
      responses:
        "200":
          description: delete successfuly
        "404":
          description: Resource not found
        default:
          description: Exception happened!
      x-swagger-router-controller: Quotation


  /NewProject:
      post:
        tags:
        - Project
        description: Start the project
        operationId: newProjectPOST
        parameters:
        - name: QuotationRequestId
          in: query
          description: Id of the quotation request
          required: true
          style: form
          explode: true
          schema:
            type: integer
          example: 1
        responses:
          "200":
            description: ok
          default:
            description: Exception happened!
        x-swagger-router-controller: Project
components:
  schemas:
    Quotation:
      properties:
        id:
          type: integer
          example: 10
        servicePrice:
          type: number
          description: the price for the service
          example: 1000
        duration:
          type: integer
          description: duration in days
          example: 10
        startDate:
          type: string
          description: the date that
          example: 11/10/2023
      description: Model containg the quotation offered by the renovation company
      example:
        duration: 10
        servicePrice: 1000
        id: 10
        startDate: 11/10/2023
