openapi: 3.0.2
info:
  title: PlumberBrothers
  version: "1.0"
servers:
  - url: https://api.server.test/v1
tags:
  - name: RequestForQuotation
    description: Request for quoation
  - name: Project

paths:
  /NewRequestForQuotation:
    post:
      tags:
        - RequestForQuotation
      summary: Recives a new request for quotation from a HRC company and responds with a Quotation
      description: A HRC company can send a request for quotation via this API. PlumberBrothers returns a quotation object that contains a status field which indicates wethere request was accepted or rejected. In the event that the request is accepted the object contains the informayion about the Quotation. 
      operationId: NewRequestForQuotationPOST
      parameters:
        - name: Address
          in: query
          description: Address of the property
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: StartDate
          in: query
          description: The Date that the company will start the project
          required: true
          style: form
          explode: true
          schema:
            type: string
          example: 10/10/2023
        - name: Duration
          in: query
          description: Project duration in days
          required: true
          style: form
          explode: true
          schema:
            type: integer
          example: 60
        - name: Budget
          in: query
          description: Max budget allocated by the houseowner to the project in Euroes
          required: true
          style: form
          explode: true
          schema:
            type: number
          example: 1000
      responses:
        "200":
          description: Quotation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quotation'
        "202":
          description: Quotation not ready yet
        default:
          description: Exception happened!
      x-swagger-router-controller: Quotation

  /NewProject:
      post:
        tags:
        - Project
        summary: Request to start a project
        description: In the event that a HRC decides PlumberBrothers as the winner, the HRC informs PlumberBrothersto start working on the project.
        operationId: newProjectPOST
        parameters:
        - name: id
          in: query
          description: Id of the quotation request
          required: true
          style: form
          explode: true
          schema:
            type: integer
          example: 1
        responses:
          "200":
            description: ok
          default:
            description: Exception happened!
        x-swagger-router-controller: Project

  /ProjectCompletionStatus/{id}:
    get:
      tags:
      - Project
      summary: Gets completion status of the project
      description: The HRC company can check wether the project is completed or not.
      operationId: projectCompletionStatusIdGET
      parameters:
      - name: id
        in: path
        description: Id of the quotation request
        required: true
        style: simple
        explode: false
        schema:
          type: integer
        example: 1
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: boolean
                x-content-type: application/json
        default:
          description: Exception happened!
      x-swagger-router-controller: Project

components:
  schemas:
    Quotation:
      properties:
        id:
          type: integer
          example: 10
        status:
          type: boolean
          example: true
          description: Request is Accepted (True) / Request is Rejected (False) 
        servicePrice:
          type: number
          description: the price for the service
          example: 1000
        duration:
          type: integer
          description: duration in days
          example: 10
        startDate:
          type: string
          description: the date that
          example: 11/10/2023
      description: Model containg the quotation offered by the renovation company
      example:
        duration: 10
        servicePrice: 1000
        id: 10
        startDate: 11/10/2023
