openapi: "3.0.2"
info:
  title: AwsomeConstructorCompany
  version: "1.0"
servers:
  - url: https://api.server.test/v1
tags:
  - name: Quotation
    description: Everything about your quoation

  - name: Project
    description: Everything about your Project

paths:
  /NewQuotation:
    post:
      tags:
        - Quotation
      description: "Recives a quotation request from a HRC company"
      parameters: 
        - in: query
          required: true
          name: Address
          description: Address of the property
          schema:
            type: string

        - in: query
          required: true
          name: StartDate
          description: Start Date
          example: 10/10/2023
          schema:
            type: string

        - in: query
          required: true
          name: Duration
          description: Duration in days
          example: 60
          schema: 
            type: integer

        - in: query
          required: true
          name: Budget
          description: Max budget in Euroes
          example: 1000
          schema: 
            type: number

      responses:
        "201":
          description: Request submitted successfuly.
        default:
          description: Exception happened!
  
  /EditQuotation:
    put:
      tags:
        - Quotation
      description: "Edit a request for quotation to constructor"
      parameters: 
        - in: query
          required: true
          name: QuotationRequestId
          description: Id of the quotation request
          example: 1
          schema:
            type: integer

        - in: query
          required: true
          name: Address
          description: Address of the property
          schema:
            type: string

        - in: query
          required: true
          name: StartDate
          description: Start Date
          example: 10/10/2023
          schema:
            type: string

        - in: query
          required: true
          name: Duration
          description: Duration in days
          example: 60
          schema: 
            type: integer

        - in: query
          required: true
          name: Budget
          description: Max budget in Euroes
          example: 1000
          schema: 
            type: number

      responses:
        "404":
          description: Resource not found
        "200":
          description: Changes applied successfuly
        default:
          description: Exception happened!
        

  /DeleteQuotation/{id}:
    delete:
      tags:
        - Quotation
      description: "delete a request for quotation to constructor"
      parameters: 
        - in: path
          name: QuotationRequestId
          description: Id of the quotation request
          required: true
          example: 1
          schema:
            type: integer

      responses:
        "404":
          description: Resource not found
        "200":
          description: delete successfuly
        default:
          description: Exception happened!

  /GetQuotation/{id}:
    get:
      tags:
        - Quotation
      description: "Offer a quoation to HRC"
      parameters: 
        - in: path
          name: QuotationRequestId
          description: Id of the quotation request
          required: true
          example: 1
          schema:
            type: integer

      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Quotation'
          description: Quotation
        
        "202":
          description: Quotation not ready yet
        default:
          description: Exception happened!

  /Project:
    post: 
      tags:
        - Project
      description: Start the project
      parameters:
        - in: query
          name: QuotationRequestId
          description: Id of the quotation request
          required: true
          example: 1
          schema:
            type: integer
      
      responses: 
        "200":
          description: ok
        default:
          description: Exception happened!

  /ProjectCompletedStatus/{id}:
    get:
      tags:
        - Project
      description: Gets completion status of the project
      parameters:
        - in: path
          name: QuotationRequestId
          description: Id of the quotation request
          required: true
          example: 1
          schema:
            type: integer
      
      responses: 
        "200":
          content:
            application/json:
              schema:
                type: boolean
          description: Ok
        default:
          description: Exception happened!


components:
  schemas:
    Quotation:
      description: Model containg the quotation offered by the renovation company
      properties: 
        id:
          type: integer
          example: 10
        servicePrice:
          description: the price for the service
          type: number
          example: 1000
        duration:
          description: duration in days
          type: integer
          example: 10
        startDate:
          description: the date that 
          type: string
          example: 11/10/2023
          