/*
 * AwsomeConstructorCompany
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using AwsomeConstructor.Attributes;

using Microsoft.AspNetCore.Authorization;
using AwsomeConstructor.Models;

namespace AwsomeConstructor.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class ProjectApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Start the project</remarks>
        /// <param name="quotationRequestId">Id of the quotation request</param>
        /// <response code="200">ok</response>
        /// <response code="0">Exception happened!</response>
        [HttpPost]
        [Route("/v1/NewProject")]
        [ValidateModelState]
        [SwaggerOperation("NewProjectPOST")]
        public virtual IActionResult NewProjectPOST([FromQuery][Required()]int? quotationRequestId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Gets completion status of the project</remarks>
        /// <param name="id">Id of the quotation request</param>
        /// <response code="200">Ok</response>
        /// <response code="0">Exception happened!</response>
        [HttpGet]
        [Route("/v1/ProjectCompletionStatus/{id}")]
        [ValidateModelState]
        [SwaggerOperation("ProjectCompletionStatusIdGET")]
        [SwaggerResponse(statusCode: 200, type: typeof(bool?), description: "Ok")]
        public virtual IActionResult ProjectCompletionStatusIdGET([FromRoute][Required]int? id)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(bool?));

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);
            string exampleJson = null;
            exampleJson = "true";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<bool?>(exampleJson)
                        : default(bool?);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
