#!/bin/bash

node CheckRequestFeasibilityWorker.js&
sleep 1
node InformHouseHolderAboutFeasbilityOfRenovationRequestWorker.js&
sleep 1
node FindPossibleWorkersWorker.js&
sleep 1

node PlumberQuotationRecievedWorker.js&
sleep 1
node StorePlumberQuotationInDBMSWorker.js&
sleep 1
node SelectBestWorkerAmongPlumbersAutomaticallyWorker.js&
sleep 1
node SendaStartProjectRequestToTheWinnerPlumberWorker.js&
sleep 1

node ElectricianQuotationReceivedWorker.js&
sleep 1
node StoreElectricianQuotationInDBMSWorker.js&
sleep 1
node SelectBestWorkerAmongElectriciansAutomaticallyWorker.js&
sleep 1
node SendAStartProjectRequestToTheWinnerElectricianWorker.js&
sleep 1

node SendEditRequestForQuotationToConstructorWorker.js&
sleep 1
node SecondRequestForQuotationSentToConstructorWorker.js&
sleep 1
node DeleteThisConstructorFromListOfPossibleWorkersWorker.js&
sleep 1
node StoreConstructorQuotationInDBMSWorker.js&
sleep 1
node SelectBestWorkerAmongConstructorsAutomaticallyWorker.js&
sleep 1
node SendAStartProjectRequestToWinnerConstructorWorker.js&
sleep 1
node SendARequestToConstructorToCheckIfProjectIsFinishedWorker.js&
sleep 1

node NotifyHouseHolderToCompletePaymentWorker.js&
sleep 1
#node FinishPaymentWorker.js&