openapi: 3.0.2
info:
  title: AwsomeConstructorCompany
  version: "1.0"
servers:
- url: https://api.server.test/v1
tags:
- name: RequestForQuotation
  description: Request for quotation
- name: Project

paths:
  /RequestForQuotation:
    post:
      tags:
      - RequestForQuotation
      summary: Receives a new request for quotation  from a HRC company and responds whether the request was submitted or not
      description: A HRC can sends a request for quotation via this API. AwsomeConstructor return whether the request was submitted or an exception happened.
      operationId: RequestForQuotationPOST
      requestBody:
        description: RequestForQuotation
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestForQuotation'
      responses:
        "201":
          description: Request submitted successfully.
        default:
          description: Exception happened!
      x-swagger-router-controller: Quotation

  /RequestForQuotation/{id}:
    put:
      tags:
      - RequestForQuotation
      summary: Receives a request for editing the quotation request with specific id from a HRC company and responds whether the request was submitted or not
      description: A HRC can sends a request for editing the request for quoation with specific id  via this API. AwsomeConstructor return whether the request was submitted or an exception happened.
      operationId: RequestForQuotationPUT
      parameters:
      - name: id
        in: path
        description: Id of the quotation request
        required: true
        explode: true
        schema:
          type: integer
        example: 1
      requestBody:
        description: RequestForQuotation
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestForQuotation'
      responses:
        "200":
          description: Changes applied successfully
        "404":
          description: Resource not found
        default:
          description: Exception happened!
      x-swagger-router-controller: Quotation

    delete:
      tags:
      - RequestForQuotation
      summary: Receives a request for deleting the quotation request with specific id from a HRC company and responds whether the quotation was deleted or exception happened.
      description: A HRC can sends a request for editing the request for quotation with specific id via this API. AwesomeConstructor return whether the request was deleted or exception happened.
      operationId: RequestForQuotationIdDELETE
      parameters:
      - name: id
        in: path
        description: Id of the quotation request
        required: true
        style: simple
        explode: false
        schema:
          type: integer
        example: 1
      responses:
        "200":
          description: Deleted successfully
        "404":
          description: Resource not found
        default:
          description: Exception happened!
      x-swagger-router-controller: Quotation

  /Quotation/{id}:
    get:
      tags:
      - RequestForQuotation
      summary: Receives a request for offering the quotation of the request for quotation with specific id from a HRC company and responds with the Quotation.
      description: A HRC can sends a request for offering the Quotation of the request for quotation with specific id via this API. AwesomeConstructor responds with the Quotation.
      operationId: QuotationIdGET
      parameters:
      - name: id
        in: path
        description: Id of the quotation request
        required: true
        style: simple
        explode: false
        schema:
          type: integer
        example: 1
      responses:
        "200":
          description: Quotation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quotation'
        "202":
          description: Quotation not ready yet
        default:
          description: Exception happened!
      x-swagger-router-controller: Quotation

  /Project:
    post:
      tags:
      - Project
      summary: Request to start the project
      description: In the event that a HRC decides AwesomeConstructor as the winner, the HRC informs PlumberBrothers start working on the project.
      operationId: ProjectPOST
      requestBody:
        description: RequestForQuotation
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        "200":
          description: ok
        default:
          description: Exception happened!
      x-swagger-router-controller: Project

  /Project/{id}:
    get:
      tags:
      - Project
      summary: Gets completion status of the project
      description: The HRC company can check wether the project is completed or not.  
      operationId: projectGET
      parameters:
      - name: id
        in: path
        description: Id of the quotation request
        required: true
        style: simple
        explode: false
        schema:
          type: integer
        example: 1
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: boolean
                x-content-type: application/json
        default:
          description: Exception happened!
      x-swagger-router-controller: Project

components:
  schemas:
    RequestForQuotation:
      properties:
        Address:
          description: Address of the property
          type: string
        StartDate:
          description: Start Date
          type: string
          example: 10/10/2023
        Duration:
          description: Duration in days
          type: integer
          example: 60
        Budget:
          description: Max budget in Euros
          type: number
          example: 1000
    Quotation:
      properties:
        id:
          type: integer
          example: 10
        servicePrice:
          type: number
          description: the price for the service
          example: 1000
        duration:
          type: integer
          description: duration in days
          example: 10
        startDate:
          type: string
          description: the date that
          example: 11/10/2023
      description: Model containing the quotation offered by the renovation company
      example:
        duration: 10
        servicePrice: 1000
        id: 10
        startDate: 11/10/2023
    Project:
      properties:
        id:
          type: integer
          example: 10
