/*
 * AwsomeElectricians
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class RequestForQuotationApiController : ControllerBase
    { 
        /// <summary>
        /// Recives a request for deleting the quotation request with specific id from a HRC company and responds whether the quoation was deleted or exception happened.
        /// </summary>
        /// <remarks>A HRC can sends a request for editing the request for quoation with specific id via this API. AwsomeConstructor return whether the request was deleted or exception happened.</remarks>
        /// <param name="id">Id of the quotation request</param>
        /// <response code="200">delete successfuly</response>
        /// <response code="404">Resource not found</response>
        /// <response code="0">Exception happened!</response>
        [HttpDelete]
        [Route("/v1/RequestForQuotation/{id}")]
        [ValidateModelState]
        [SwaggerOperation("DeleteRequestForQuotationIdDELETE")]
        public virtual IActionResult DeleteRequestForQuotationIdDELETE([FromRoute][Required]int? id)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Recives a request for editing the quotation request with specific id from a HRC company and responds whether the request was submitted or not
        /// </summary>
        /// <remarks>A HRC can sends a request for editing the request for quoation with specific id  via this API. AwsomeConstructor return whether the request was submitted or an exception happened.</remarks>
        /// <param name="body">RequestForQuotation</param>
        /// <param name="id">Id of the quotation request</param>
        /// <response code="200">Changes applied successfuly</response>
        /// <response code="404">Resource not found</response>
        /// <response code="0">Exception happened!</response>
        [HttpPut]
        [Route("/v1/RequestForQuotation/{id}")]
        [ValidateModelState]
        [SwaggerOperation("EditQuotationPUT")]
        public virtual IActionResult EditQuotationPUT([FromBody]RequestForQuotation body, [FromRoute][Required]int? id)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Recives a new request for quotation from a HRC company and responds whether the request was submitted or not
        /// </summary>
        /// <remarks>A HRC can sends a request for quoation via this API. AwsomeConstructor return whether the request was submitted or an exception happened.</remarks>
        /// <param name="body">RequestForQuotation</param>
        /// <response code="201">Request submitted successfuly.</response>
        /// <response code="0">Exception happened!</response>
        [HttpPost]
        [Route("/v1/RequestForQuotation")]
        [ValidateModelState]
        [SwaggerOperation("NewQuotationRequestPOST")]
        public virtual IActionResult NewQuotationRequestPOST([FromBody]RequestForQuotation body)
        { 
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201);

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);

            throw new NotImplementedException();
        }
    }
}
